console.log("Hello Bcs Academy");
var x = 5;
var y = 2;
console.log(x + y);
console.log(x - y);
console.log(x ** y);
true;
false;
console.log(true & false);
console.log(true & true);
a = "robin";
b = "r";
console.log(a + b);
console.log(typeof a);
c = true;
d = false;
console.log(c & d);
console.log(c || d);
r = 10;
p = 9;
console.log(r == p);
console.log(r !== p);
console.log(r > p);
console.log(r >= p);
console.log(!r >= p);
console.log(r < p);
console.log(r <= p);
console.log(!r <= p);
m = true;
n = false;
console.log(m & n);
console.log(m || n);
console.log(7 != 8 && 4 >= 3 && 3 != 9 && !(4 > 1));
